
assault_rifles = [
    {"name": "AK-47", "description": "Legendary Soviet assault rifle, 7.62×39mm, extremely reliable.", "department_name": "Assault Rifles"},
    {"name": "M16", "description": "Standard American assault rifle, 5.56×45mm NATO, used by US military.", "department_name": "Assault Rifles"},
    {"name": "FN SCAR-L", "description": "Belgian modular rifle, 5.56×45mm, used by special forces.", "department_name": "Assault Rifles"},
    {"name": "Steyr AUG", "description": "Austrian bullpup rifle, 5.56×45mm, features integral optic.", "department_name": "Assault Rifles"},
    {"name": "HK416", "description": "German AR-15-based rifle with improved gas system, 5.56×45mm.", "department_name": "Assault Rifles"},
    {"name": "Galil ACE", "description": "Modern Israeli rifle, available in multiple calibers.", "department_name": "Assault Rifles"},
    {"name": "CZ 805 BREN", "description": "Czech modular rifle, supports 5.56×45mm and 7.62×39mm.", "department_name": "Assault Rifles"},
    {"name": "Tavor X95", "description": "Israeli compact bullpup, 5.56×45mm, IDF standard issue.", "department_name": "Assault Rifles"},
    {"name": "AK-12", "description": "Latest Russian Kalashnikov, 5.45×39mm, modernized design.", "department_name": "Assault Rifles"},
    {"name": "FN F2000", "description": "Belgian futuristic bullpup, 5.56×45mm, rear ejection.", "department_name": "Assault Rifles"},
    {"name": "QBZ-95", "description": "Chinese bullpup, 5.8×42mm, service rifle of PLA.", "department_name": "Assault Rifles"},
    {"name": "Beretta ARX160", "description": "Italian modular rifle, 5.56×45mm, quick-change barrel.", "department_name": "Assault Rifles"},
    {"name": "SIG SG 550", "description": "Swiss precision rifle, 5.56×45mm, renowned reliability.", "department_name": "Assault Rifles"},
    {"name": "IWI ARAD", "description": "Modern Israeli rifle, 5.56×45mm, short-stroke piston.", "department_name": "Assault Rifles"},
    {"name": "FAMAS", "description": "French bullpup, 5.56×45mm, high rate of fire.", "department_name": "Assault Rifles"},
    {"name": "HK G36", "description": "German polymer rifle, 5.56×45mm, lightweight construction.", "department_name": "Assault Rifles"},
    {"name": "Type 95", "description": "Chinese bullpup, 5.8×42mm, compact service rifle.", "department_name": "Assault Rifles"},
    {"name": "FN CAL", "description": "Early Belgian 5.56×45mm rifle, precursor to FN FNC.", "department_name": "Assault Rifles"},
    {"name": "AK-74", "description": "Modernized AK, 5.45×39mm, lighter and faster than AK-47.", "department_name": "Assault Rifles"},
    {"name": "M4 Carbine", "description": "Shortened M16, 5.56×45mm, widely used by US forces.", "department_name": "Assault Rifles"},
    {"name": "SA80 L85", "description": "British bullpup, 5.56×45mm, improved over time.", "department_name": "Assault Rifles"},
    {"name": "SIG MCX", "description": "American modular rifle, supports various calibers.", "department_name": "Assault Rifles"},
    {"name": "T91", "description": "Taiwanese rifle, 5.56×45mm, short-stroke piston.", "department_name": "Assault Rifles"},
    {"name": "Valmet M76", "description": "Finnish AK-based rifle, 5.56×45mm, Western improvements.", "department_name": "Assault Rifles"},
    {"name": "AR-15", "description": "American semi-auto rifle, 5.56×45mm, popular with civilians.", "department_name": "Assault Rifles"},
    {"name": "FN FNC", "description": "Belgian 5.56×45mm rifle, improved gas system.", "department_name": "Assault Rifles"},
    {"name": "IMI Galil", "description": "Israeli 5.56×45mm rifle, AK-based with enhancements.", "department_name": "Assault Rifles"},
    {"name": "Heckler & Koch G3", "description": "German 7.62×51mm battle rifle, widely exported.", "department_name": "Assault Rifles"},
    {"name": "SIG SG 552", "description": "Compact SG 550, 5.56×45mm, ideal for urban combat.", "department_name": "Assault Rifles"},
    {"name": "FN SCAR-H", "description": "Heavy version of FN SCAR, 7.62×51mm, long-range capable.", "department_name": "Assault Rifles"}
]

handguns = [
    {"name": "Glock 17", "description": "Popular Austrian 9mm semi-automatic pistol, widely used by police worldwide.", "department_name": "Handguns"},
    {"name": "Beretta 92FS", "description": "Classic Italian full-size 9mm pistol, military and police standard.", "department_name": "Handguns"},
    {"name": "SIG Sauer P320", "description": "Modular 9mm semi-automatic pistol, chosen by US Army.", "department_name": "Handguns"},
    {"name": "Smith & Wesson M&P Shield", "description": "Compact and reliable American 9mm pistol, great for concealed carry.", "department_name": "Handguns"},
    {"name": "Colt M1911", "description": "Legendary .45 ACP American pistol, military icon for decades.", "department_name": "Handguns"},
    {"name": "Walther PPQ", "description": "German 9mm polymer-framed pistol, known for its trigger.", "department_name": "Handguns"},
    {"name": "CZ 75", "description": "Czech full-size 9mm pistol, all-steel, highly regarded for accuracy.", "department_name": "Handguns"},
    {"name": "Springfield XD-S", "description": "Single-stack subcompact 9mm pistol, slim and lightweight.", "department_name": "Handguns"},
    {"name": "Heckler & Koch VP9", "description": "Striker-fired 9mm German pistol, highly ergonomic design.", "department_name": "Handguns"},
    {"name": "FN Five-seveN", "description": "Unique 5.7×28mm pistol, lightweight polymer frame.", "department_name": "Handguns"},
    {"name": "Ruger SR9", "description": "American 9mm striker-fired pistol, slim and affordable.", "department_name": "Handguns"},
    {"name": "Taurus G2C", "description": "Brazilian compact 9mm, popular for concealed carry.", "department_name": "Handguns"},
    {"name": "Glock 19", "description": "Compact version of the Glock 17, 9mm, extremely popular.", "department_name": "Handguns"},
    {"name": "Beretta PX4 Storm", "description": "Italian 9mm with rotating barrel design, modular features.", "department_name": "Handguns"},
    {"name": "SIG Sauer P226", "description": "Full-size 9mm, widely used by military and law enforcement.", "department_name": "Handguns"},
    {"name": "Kimber Custom II", "description": "High-quality 1911-style .45 ACP, American made.", "department_name": "Handguns"},
    {"name": "Browning Hi-Power", "description": "Classic Belgian 9mm, used by militaries worldwide.", "department_name": "Handguns"},
    {"name": "Glock 43", "description": "Ultra-compact single-stack 9mm, ideal for deep concealment.", "department_name": "Handguns"},
    {"name": "S&W Model 686", "description": "Classic .357 Magnum American revolver, stainless steel.", "department_name": "Handguns"},
    {"name": "Ruger GP100", "description": ".357 Magnum double-action revolver, robust and reliable.", "department_name": "Handguns"},
    {"name": "Colt Python", "description": "Legendary .357 Magnum revolver, known for its smooth trigger.", "department_name": "Handguns"},
    {"name": "SIG Sauer P365", "description": "High-capacity micro-compact 9mm, very popular for EDC.", "department_name": "Handguns"},
    {"name": "Walther P99", "description": "German 9mm DA/SA pistol, innovative features.", "department_name": "Handguns"},
    {"name": "Springfield Armory Hellcat", "description": "Micro-compact 9mm with impressive capacity.", "department_name": "Handguns"},
    {"name": "FN 509", "description": "American 9mm striker-fired, robust and duty-ready.", "department_name": "Handguns"},
    {"name": "CZ P-10 C", "description": "Czech 9mm polymer striker-fired, excellent ergonomics.", "department_name": "Handguns"},
    {"name": "Taurus Judge", "description": "Versatile revolver fires both .410 shotgun and .45 Colt.", "department_name": "Handguns"},
    {"name": "Desert Eagle", "description": "Iconic large-caliber semi-auto, available in .50 AE.", "department_name": "Handguns"},
    {"name": "Glock 21", "description": "Full-size .45 ACP polymer pistol, high capacity.", "department_name": "Handguns"},
    {"name": "Smith & Wesson Model 500", "description": "Extremely powerful .500 S&W Magnum revolver.", "department_name": "Handguns"},
]

ammunition = [
    {"name": "9mm Luger", "description": "Most popular handgun cartridge, used in pistols and submachine guns.", "department_name": "Ammunition"},
    {"name": ".45 ACP", "description": "Large caliber round for 1911s and other handguns.", "department_name": "Ammunition"},
    {"name": ".357 Magnum", "description": "Powerful revolver cartridge, also fits some carbines.", "department_name": "Ammunition"},
    {"name": ".40 S&W", "description": "Popular law enforcement pistol round, between 9mm and .45 ACP.", "department_name": "Ammunition"},
    {"name": ".38 Special", "description": "Classic revolver cartridge, known for mild recoil.", "department_name": "Ammunition"},
    {"name": ".380 ACP", "description": "Compact handgun round, fits many pocket pistols.", "department_name": "Ammunition"},
    {"name": "5.56×45mm NATO", "description": "Standard NATO rifle round for AR-15/M16 and similar rifles.", "department_name": "Ammunition"},
    {"name": "7.62×39mm", "description": "Iconic AK-47 rifle cartridge, known for reliability.", "department_name": "Ammunition"},
    {"name": "7.62×51mm NATO", "description": "Battle rifle and sniper cartridge, used in G3, SCAR-H.", "department_name": "Ammunition"},
    {"name": ".308 Winchester", "description": "Commercial version of 7.62 NATO, used in hunting and tactical rifles.", "department_name": "Ammunition"},
    {"name": ".223 Remington", "description": "Civilian counterpart to 5.56 NATO, fits most AR-style rifles.", "department_name": "Ammunition"},
    {"name": "5.45×39mm", "description": "Soviet round, standard for AK-74 rifles.", "department_name": "Ammunition"},
    {"name": "5.7×28mm", "description": "High-velocity round for FN Five-seveN and P90.", "department_name": "Ammunition"},
    {"name": ".50 AE", "description": "Extreme power for Desert Eagle and similar pistols.", "department_name": "Ammunition"},
    {"name": ".22 LR", "description": "Popular rimfire for target, training, and plinking.", "department_name": "Ammunition"},
    {"name": ".32 ACP", "description": "Small caliber pistol round, compact and low recoil.", "department_name": "Ammunition"},
    {"name": ".25 ACP", "description": "Very small caliber round for pocket pistols.", "department_name": "Ammunition"},
    {"name": "10mm Auto", "description": "Powerful semi-auto pistol round, preferred for hunting.", "department_name": "Ammunition"},
    {"name": ".44 Magnum", "description": "Extremely powerful revolver cartridge, famous from movies.", "department_name": "Ammunition"},
    {"name": "7.62×25mm Tokarev", "description": "High-velocity round for Russian pistols and SMGs.", "department_name": "Ammunition"},
    {"name": ".45 Colt", "description": "Classic cartridge for revolvers and lever-action rifles.", "department_name": "Ammunition"},
    {"name": ".410 Bore", "description": "Small shotgun shell, fits revolvers like the Taurus Judge.", "department_name": "Ammunition"},
    {"name": "12 Gauge", "description": "Most common shotgun shell, also used in combat shotguns.", "department_name": "Ammunition"},
    {"name": "20 Gauge", "description": "Smaller shotgun shell, lower recoil than 12 gauge.", "department_name": "Ammunition"},
    {"name": "6.5mm Creedmoor", "description": "Modern long-range rifle cartridge, precision shooting.", "department_name": "Ammunition"},
    {"name": ".357 SIG", "description": "Bottle-necked pistol round, high velocity, flat shooting.", "department_name": "Ammunition"},
    {"name": ".38 Super", "description": "High-pressure 1911 cartridge, popular in competition.", "department_name": "Ammunition"},
    {"name": ".300 AAC Blackout", "description": "AR-15 compatible, optimized for suppressed fire.", "department_name": "Ammunition"},
    {"name": "8mm Mauser", "description": "Historic military rifle cartridge, used in Mauser rifles.", "department_name": "Ammunition"},
    {"name": "7.62×54mmR", "description": "Russian rifle cartridge, used in Dragunov, Mosin-Nagant.", "department_name": "Ammunition"},
]

rifle_scopes = [
    {"name": "Leupold VX-3i 3.5-10x40", "description": "High-quality American variable scope, renowned for brightness and durability.", "department_name": "Rifle Scopes"},
    {"name": "Nightforce ATACR 5-25x56", "description": "Premium long-range scope, excellent clarity, used by professionals.", "department_name": "Rifle Scopes"},
    {"name": "Vortex Viper PST Gen II 5-25x50", "description": "Tactical long-range scope, EBR-2C reticle, first focal plane.", "department_name": "Rifle Scopes"},
    {"name": "Bushnell Elite Tactical DMR II 3.5-21x50", "description": "Rugged tactical optic, ED Prime glass, proven in competitions.", "department_name": "Rifle Scopes"},
    {"name": "Schmidt & Bender PM II 5-25x56", "description": "German-made high-precision scope, used by military snipers.", "department_name": "Rifle Scopes"},
    {"name": "Zeiss Conquest V4 6-24x50", "description": "Versatile German hunting and tactical scope, bright and reliable.", "department_name": "Rifle Scopes"},
    {"name": "Trijicon ACOG 4x32", "description": "Fixed power combat optic, fiber optic illumination, US military standard.", "department_name": "Rifle Scopes"},
    {"name": "Primary Arms SLx 3-18x50", "description": "Affordable precision rifle scope with ACSS reticle.", "department_name": "Rifle Scopes"},
    {"name": "Swarovski Z6i 2.5-15x56", "description": "Luxury European hunting scope, outstanding light transmission.", "department_name": "Rifle Scopes"},
    {"name": "Sig Sauer Tango6 5-30x56", "description": "Extreme long-range precision scope, HDX optics.", "department_name": "Rifle Scopes"},
    {"name": "Vortex Crossfire II 4-12x44", "description": "Entry-level variable scope, great value for hunting rifles.", "department_name": "Rifle Scopes"},
    {"name": "Burris Fullfield E1 4.5-14x42", "description": "Solid hunting scope with Ballistic Plex reticle.", "department_name": "Rifle Scopes"},
    {"name": "Kahles K624i 6-24x56", "description": "Austrian tactical scope, high precision and robust design.", "department_name": "Rifle Scopes"},
    {"name": "Athlon Ares ETR 4.5-30x56", "description": "First focal plane competition scope, excellent tracking.", "department_name": "Rifle Scopes"},
    {"name": "Leica Magnus 2.4-16x56", "description": "Premium European scope, crystal-clear glass.", "department_name": "Rifle Scopes"},
    {"name": "Meopta Optika6 5-30x56", "description": "Long-range Czech scope, high-definition optics.", "department_name": "Rifle Scopes"},
    {"name": "EOTech Vudu 5-25x50", "description": "Tactical precision rifle scope with illuminated reticle.", "department_name": "Rifle Scopes"},
    {"name": "Holosun HS510C", "description": "Open reflex sight, solar power, suitable for AR-style rifles.", "department_name": "Rifle Scopes"},
    {"name": "Aimpoint CompM4", "description": "Military-grade red dot sight, rugged and reliable.", "department_name": "Rifle Scopes"},
    {"name": "Trijicon AccuPoint 2.5-10x56", "description": "Illuminated hunting scope, battery-free fiber optic.", "department_name": "Rifle Scopes"}
]

pistol_sights = [
    {"name": "Trijicon RMR Type 2", "description": "Rugged red dot sight, widely used on defensive and competition pistols.", "department_name": "Pistol Sights"},
    {"name": "Leupold DeltaPoint Pro", "description": "Clear, durable reflex sight for rapid target acquisition on handguns.", "department_name": "Pistol Sights"},
    {"name": "Holosun HS507C X2", "description": "Feature-rich micro red dot, solar backup, long battery life.", "department_name": "Pistol Sights"},
    {"name": "Vortex Venom Red Dot", "description": "Affordable and compact red dot sight, easy to mount on pistols.", "department_name": "Pistol Sights"},
    {"name": "Burris FastFire 3", "description": "Lightweight reflex sight, suitable for pistols and shotguns.", "department_name": "Pistol Sights"},
    {"name": "SIG Sauer Romeo1Pro", "description": "Tough, high-performance reflex sight, fast on target.", "department_name": "Pistol Sights"},
    {"name": "Swampfox Sentinel", "description": "Ultra-compact red dot, perfect for subcompact pistols.", "department_name": "Pistol Sights"},
    {"name": "Crimson Trace CTS-1550", "description": "Entry-level red dot sight for everyday carry pistols.", "department_name": "Pistol Sights"},
    {"name": "TruGlo TFX Pro Sights", "description": "Tritium/fiber-optic iron sights, bright day and night.", "department_name": "Pistol Sights"},
    {"name": "Meprolight Tru-Dot Night Sights", "description": "Reliable night sights, green tritium, quick target acquisition.", "department_name": "Pistol Sights"},
    {"name": "AmeriGlo Pro-IDOT", "description": "Simple iron sight upgrade for faster sight alignment.", "department_name": "Pistol Sights"},
    {"name": "XS Sights DXT2 Big Dot", "description": "Large dot front sight, excellent for defensive shooting.", "department_name": "Pistol Sights"},
    {"name": "Heinie Straight Eight", "description": "Vertical dot iron sights, favored by competitive shooters.", "department_name": "Pistol Sights"},
    {"name": "Glock OEM Night Sights", "description": "Factory-installed tritium sights, glowing in low light.", "department_name": "Pistol Sights"},
    {"name": "HiViz Litewave", "description": "Interchangeable fiber-optic iron sights for pistols.", "department_name": "Pistol Sights"},
]

grips = [
    {"name": "Hogue Rubber Grip", "description": "Ergonomic, textured rubber grip for pistols and revolvers, absorbs recoil.", "department_name": "Grips"},
    {"name": "Magpul MOE AR-15 Grip", "description": "Popular drop-in polymer grip for AR-15 rifles, comfortable and durable.", "department_name": "Grips"},
    {"name": "Pachmayr Diamond Pro", "description": "Recoil-absorbing grip for revolvers, checkered for extra control.", "department_name": "Grips"},
    {"name": "Ergo SureGrip", "description": "Soft, non-slip grip for rifles and shotguns, improves comfort.", "department_name": "Grips"},
    {"name": "VZ G10 Tactical Grips", "description": "Aggressively textured G10 grips for 1911 pistols, excellent in all weather.", "department_name": "Grips"},
    {"name": "Talon Grips", "description": "Stick-on grip enhancements for pistols, improves texture and control.", "department_name": "Grips"},
    {"name": "Fab Defense AGR-47", "description": "Upgraded AK-47 grip, ergonomic with internal storage.", "department_name": "Grips"},
    {"name": "Pearce Grip Extension", "description": "Magazine grip extension for compact and subcompact pistols.", "department_name": "Grips"},
    {"name": "Wilson Combat 1911 Grips", "description": "High-end custom grips for 1911 pistols, various textures.", "department_name": "Grips"},
    {"name": "BCM Gunfighter Grip Mod 3", "description": "Modern AR-15 grip with improved angle and storage compartment.", "department_name": "Grips"},
    {"name": "Strike Industries Enhanced Pistol Grip", "description": "Lightweight, textured AR grip, comfortable for long shooting sessions.", "department_name": "Grips"},
    {"name": "Lyman Pachmayr Gripper", "description": "Rubber revolver grip, designed for target shooting.", "department_name": "Grips"},
    {"name": "Glock OEM Beavertail Grip", "description": "Factory beavertail add-on for Glock pistols, reduces slide bite.", "department_name": "Grips"},
    {"name": "Hogue Tamer Shotgun Grip", "description": "Shock-absorbing grip for shotguns, reduces felt recoil.", "department_name": "Grips"},
    {"name": "Mako Group AR-15 Pistol Grip", "description": "Adjustable AR-15 grip for custom fit and feel.", "department_name": "Grips"},
]

stocks = [
    {"name": "Magpul MOE Carbine Stock", "description": "Lightweight, adjustable AR-15/M4 carbine stock, durable and popular.", "department_name": "Stocks"},
    {"name": "Magpul PRS Gen3", "description": "Precision-adjustable stock for AR-15/AR-10 rifles, used for long-range shooting.", "department_name": "Stocks"},
    {"name": "FAB Defense GL-Core", "description": "Tactical collapsible stock for AR platforms, rugged and comfortable.", "department_name": "Stocks"},
    {"name": "BCM Gunfighter Stock", "description": "Minimalist, snag-free AR-15 stock, highly regarded by professionals.", "department_name": "Stocks"},
    {"name": "Magpul ACS-L", "description": "Slim, storage-capable stock for AR-15 rifles, comfortable cheek weld.", "department_name": "Stocks"},
    {"name": "Luth-AR MBA-3", "description": "Modular, adjustable stock for precision shooting and competition.", "department_name": "Stocks"},
    {"name": "Daniel Defense Collapsible Stock", "description": "High-quality collapsible stock, fits Mil-Spec buffer tubes.", "department_name": "Stocks"},
    {"name": "Hogue OverMolded Stock", "description": "Rubberized stock for rifles and shotguns, absorbs recoil.", "department_name": "Stocks"},
    {"name": "ATI Strikeforce Stock", "description": "Tactical folding stock for rifles and shotguns, versatile and adjustable.", "department_name": "Stocks"},
    {"name": "Magpul Hunter 700", "description": "Precision stock for Remington 700 rifles, modular and ergonomic.", "department_name": "Stocks"},
    {"name": "Choate Ultimate Sniper Stock", "description": "Heavy-duty adjustable stock for precision bolt-action rifles.", "department_name": "Stocks"},
    {"name": "Mesa Tactical Urbino Stock", "description": "Tactical shotgun stock, adjustable and robust.", "department_name": "Stocks"},
    {"name": "Boyds At-One Thumbhole", "description": "Adjustable laminate stock, fits many rifle platforms.", "department_name": "Stocks"},
    {"name": "Magpul SGA Remington 870", "description": "Popular upgrade stock for Remington 870 shotguns.", "department_name": "Stocks"},
    {"name": "Blackhawk Knoxx SpecOps Gen III", "description": "Recoil-reducing tactical stock for shotguns.", "department_name": "Stocks"},
]

flashlights = [
    {"name": "Streamlight TLR-1 HL", "description": "High-lumen weapon light for pistols and rifles, durable and popular.", "department_name": "Flashlights"},
    {"name": "SureFire X300U-A", "description": "Premium tactical pistol light, extreme brightness and rugged build.", "department_name": "Flashlights"},
    {"name": "Olight PL-Mini 2 Valkyrie", "description": "Ultra-compact rechargeable weapon light, adjustable rail mount.", "department_name": "Flashlights"},
    {"name": "Inforce WML Gen2", "description": "Lightweight rifle-mounted flashlight with momentary/constant modes.", "department_name": "Flashlights"},
    {"name": "Nightstick TWM-30", "description": "Full-size tactical weapon light, aluminum body, powerful output.", "department_name": "Flashlights"},
    {"name": "Streamlight ProTac HL-X", "description": "Dual fuel long gun light, fits rifles and shotguns.", "department_name": "Flashlights"},
    {"name": "Fenix PD35 TAC", "description": "Compact tactical flashlight, can be weapon mounted, multiple output levels.", "department_name": "Flashlights"},
    {"name": "Olight Baldr Pro", "description": "Weapon light with integrated green laser, high output.", "department_name": "Flashlights"},
    {"name": "SureFire Scout Light Pro", "description": "Premium long-gun flashlight, popular for AR-15 platforms.", "department_name": "Flashlights"},
    {"name": "Cloud Defensive OWL", "description": "Robust rifle light, optimized for high output and ergonomics.", "department_name": "Flashlights"},
    {"name": "Streamlight TLR-7A", "description": "Compact pistol light, ambidextrous switches, very reliable.", "department_name": "Flashlights"},
    {"name": "Fenix TK16 V2.0", "description": "Ultra-bright tactical flashlight, rail mount compatible.", "department_name": "Flashlights"},
    {"name": "Nightstick TCM-550XL", "description": "Miniature weapon light for subcompacts, powerful for its size.", "department_name": "Flashlights"},
    {"name": "Modlite PLHv2", "description": "High-performance rifle light, modular design, used by professionals.", "department_name": "Flashlights"},
    {"name": "Olight Odin Mini", "description": "Magnetic rechargeable tactical light for rifles, compact and powerful.", "department_name": "Flashlights"},
]

lasers = [
    {"name": "Crimson Trace Rail Master", "description": "Universal rail-mounted laser sight, easy to install on pistols and rifles.", "department_name": "Lasers"},
    {"name": "Viridian C5L", "description": "Green laser and tactical light combo, compact and high-visibility.", "department_name": "Lasers"},
    {"name": "Streamlight TLR-6", "description": "Compact laser/light combo, fits many subcompact pistols.", "department_name": "Lasers"},
    {"name": "LaserMax Guide Rod Laser", "description": "Internal laser sight for handguns, replaces guide rod.", "department_name": "Lasers"},
    {"name": "Sightmark LoPro Mini Combo", "description": "Laser/flashlight combo for rifles, compact and adjustable.", "department_name": "Lasers"},
    {"name": "SureFire X400U", "description": "High-output weapon light with integrated laser, very rugged.", "department_name": "Lasers"},
    {"name": "Olight Baldr Mini", "description": "Compact tactical light/green laser combo for pistols.", "department_name": "Lasers"},
    {"name": "Holosun LS117G", "description": "Class IIIa green laser for rifles, highly visible.", "department_name": "Lasers"},
    {"name": "LaserLyte V4", "description": "Universal rail-mount red laser, affordable and easy to use.", "department_name": "Lasers"},
    {"name": "Sig Sauer Lima365", "description": "Integrated trigger guard laser, designed for Sig P365 pistols.", "department_name": "Lasers"},
    {"name": "TruGlo Micro-Tac", "description": "Ultra-lightweight micro laser, fits any rail-equipped handgun.", "department_name": "Lasers"},
    {"name": "Viridian HS1", "description": "Hand stop with integrated green laser, ideal for AR-style pistols.", "department_name": "Lasers"},
    {"name": "Crimson Trace LG-401", "description": "Lasergrip for 1911 pistols, instinctive activation.", "department_name": "Lasers"},
    {"name": "NcStar Laser Sight", "description": "Basic universal red laser sight, simple and reliable.", "department_name": "Lasers"},
    {"name": "Steiner DBAL-A3", "description": "Military-grade IR/visible laser for rifles, used by professionals.", "department_name": "Lasers"},
]
